import { ClayPalette, WidgetCustomization, SlideItem } from './types';
import courtyardImg from './assets/images/modern_school_courtyard_1790334345092.jpg';
import libraryImg from './assets/images/modern_school_library_1790334356779.jpg';
import eventRoboticsImg from './assets/images/event_robotics_1790956140260.jpg';
import eventOutdoorImg from './assets/images/event_outdoor_1790956155223.jpg';
import eventPaintingImg from './assets/images/event_painting_1790956172170.jpg';

export const COURTYARD_IMAGE = courtyardImg;
export const LIBRARY_IMAGE = libraryImg;
export const ROBOTICS_IMAGE = eventRoboticsImg;
export const OUTDOOR_IMAGE = eventOutdoorImg;
export const PAINTING_IMAGE = eventPaintingImg;

export const DEFAULT_SLIDES: SlideItem[] = [
  {
    id: 'robotics',
    url: ROBOTICS_IMAGE,
    titleEn: 'Robotics & STEM Studio',
    titleFa: 'کارگاه برنامه‌نویسی و رباتیک',
    captionEn: 'Creative algorithmic thinking & hands-on robotics',
    captionFa: 'ساخت ربات‌ها و تفکر الگوریتمی از سنین پایه',
  },
  {
    id: 'outdoor',
    url: OUTDOOR_IMAGE,
    titleEn: 'Day of Play & Discovery',
    titleFa: 'فضای سبز حیاط و بازی پرنشاط',
    captionEn: 'Open-air exploration, team games & physical joy',
    captionFa: 'محیطی شاداب، بازی‌های گروهی و نشاط کودکانه',
  },
  {
    id: 'painting',
    url: PAINTING_IMAGE,
    titleEn: 'Creative Art & Atelier',
    titleFa: 'آتلیه هنر، رنگ و خلاقیت',
    captionEn: 'Expressive watercolor, crafts & tactile pottery',
    captionFa: 'نقاشی، چرمدوزی و پرورش ذوق و قریحه هنری',
  },
  {
    id: 'courtyard',
    url: COURTYARD_IMAGE,
    titleEn: 'Smart Architecture Campus',
    titleFa: 'پردیس معماری و حیاط هوشمند',
    captionEn: 'Daylit learning studios & secure open campus',
    captionFa: 'فضایی پرنور، امن و آرام برای کاوش دانش‌آموزان',
  },
];

export const CLAY_PALETTES: Record<string, ClayPalette> = {
  sage: {
    id: 'sage',
    name: 'Sage Clay (Original)',
    nameFa: 'خاک رسی سدر (اصلی)',
    bgLight: '#EEF3EB',
    bgDark: '#DFE8DB',
    recessShadowColor: 'rgba(38, 55, 40, 0.32)',
    recessHighlightColor: 'rgba(255, 255, 255, 0.90)',
    outerShadowColor: 'rgba(48, 68, 50, 0.16)',
    textPrimary: '#1F291E',
    textSecondary: '#4A5B4C',
    accentLeaf: '#7A9176',
    btnBorder: '#647D61',
    btnHoverBg: 'rgba(100, 125, 97, 0.12)',
  },
  forest: {
    id: 'forest',
    name: 'Deep Pine & Forest',
    nameFa: 'سبز جنگلی و صنوبر کهن',
    bgLight: '#E3EDE0',
    bgDark: '#D0DEC7',
    recessShadowColor: 'rgba(25, 52, 28, 0.36)',
    recessHighlightColor: 'rgba(255, 255, 255, 0.92)',
    outerShadowColor: 'rgba(30, 60, 35, 0.18)',
    textPrimary: '#0F2615',
    textSecondary: '#364F3A',
    accentLeaf: '#4D754B',
    btnBorder: '#436941',
    btnHoverBg: 'rgba(67, 105, 65, 0.14)',
  },
  matcha: {
    id: 'matcha',
    name: 'Vibrant Matcha Green',
    nameFa: 'سبز ماتچای ژاپنی پرانرژی',
    bgLight: '#EDF5E4',
    bgDark: '#DDE8CE',
    recessShadowColor: 'rgba(35, 60, 22, 0.32)',
    recessHighlightColor: 'rgba(255, 255, 255, 0.92)',
    outerShadowColor: 'rgba(45, 75, 30, 0.16)',
    textPrimary: '#192C12',
    textSecondary: '#435C33',
    accentLeaf: '#618C47',
    btnBorder: '#56803E',
    btnHoverBg: 'rgba(86, 128, 62, 0.14)',
  },
  pistachio: {
    id: 'pistachio',
    name: 'Creamy Pistachio Pastel',
    nameFa: 'سبز پسته ای کرمی و ملایم',
    bgLight: '#F3F7ED',
    bgDark: '#E3EDDA',
    recessShadowColor: 'rgba(40, 58, 35, 0.28)',
    recessHighlightColor: 'rgba(255, 255, 255, 0.92)',
    outerShadowColor: 'rgba(50, 72, 45, 0.14)',
    textPrimary: '#20301B',
    textSecondary: '#4E6349',
    accentLeaf: '#6D9360',
    btnBorder: '#5D8251',
    btnHoverBg: 'rgba(93, 130, 81, 0.12)',
  },
  eucalyptus: {
    id: 'eucalyptus',
    name: 'Nordic Eucalyptus',
    nameFa: 'سبز اکالیپتوس و نعنایی خنک',
    bgLight: '#E7F2EF',
    bgDark: '#D4E6E1',
    recessShadowColor: 'rgba(25, 55, 50, 0.30)',
    recessHighlightColor: 'rgba(255, 255, 255, 0.92)',
    outerShadowColor: 'rgba(35, 68, 62, 0.15)',
    textPrimary: '#132B28',
    textSecondary: '#3C5B57',
    accentLeaf: '#4F847E',
    btnBorder: '#41736C',
    btnHoverBg: 'rgba(65, 115, 108, 0.14)',
  },
  emerald: {
    id: 'emerald',
    name: 'Heritage Jade & Emerald',
    nameFa: 'سبز زمردی و یشمی سلطنتی',
    bgLight: '#E0EDE6',
    bgDark: '#CCE0D5',
    recessShadowColor: 'rgba(18, 55, 40, 0.35)',
    recessHighlightColor: 'rgba(255, 255, 255, 0.92)',
    outerShadowColor: 'rgba(25, 70, 50, 0.18)',
    textPrimary: '#0C2A1E',
    textSecondary: '#2F5745',
    accentLeaf: '#387D5C',
    btnBorder: '#2D6B4E',
    btnHoverBg: 'rgba(45, 107, 78, 0.14)',
  },
  ivory: {
    id: 'ivory',
    name: 'Warm Linen & Ivory',
    nameFa: 'کتان و عاجی گرم',
    bgLight: '#F7F5EE',
    bgDark: '#ECE7DC',
    recessShadowColor: 'rgba(65, 55, 40, 0.26)',
    recessHighlightColor: 'rgba(255, 255, 255, 0.92)',
    outerShadowColor: 'rgba(70, 60, 45, 0.14)',
    textPrimary: '#2B261F',
    textSecondary: '#5E5446',
    accentLeaf: '#8D7E69',
    btnBorder: '#786955',
    btnHoverBg: 'rgba(120, 105, 85, 0.12)',
  },
  terracotta: {
    id: 'terracotta',
    name: 'Soft Terracotta',
    nameFa: 'خاک رس اخرایی لطیف',
    bgLight: '#F7EDE7',
    bgDark: '#EBDBD3',
    recessShadowColor: 'rgba(75, 45, 35, 0.28)',
    recessHighlightColor: 'rgba(255, 255, 255, 0.88)',
    outerShadowColor: 'rgba(80, 50, 40, 0.15)',
    textPrimary: '#2E1E18',
    textSecondary: '#62473D',
    accentLeaf: '#9B6D5E',
    btnBorder: '#8A5B4C',
    btnHoverBg: 'rgba(138, 91, 76, 0.12)',
  },
  mist: {
    id: 'mist',
    name: 'Porcelain Mist',
    nameFa: 'مه چینی ملایم',
    bgLight: '#ECF2F5',
    bgDark: '#DDE7ED',
    recessShadowColor: 'rgba(35, 55, 70, 0.26)',
    recessHighlightColor: 'rgba(255, 255, 255, 0.92)',
    outerShadowColor: 'rgba(40, 65, 80, 0.14)',
    textPrimary: '#1A2730',
    textSecondary: '#4A5B67',
    accentLeaf: '#688496',
    btnBorder: '#516E82',
    btnHoverBg: 'rgba(81, 110, 130, 0.12)',
  },
  rose: {
    id: 'rose',
    name: 'Dusty Rose Clay',
    nameFa: 'خاک رس رُز کویری',
    bgLight: '#F5ECF0',
    bgDark: '#EADCE2',
    recessShadowColor: 'rgba(70, 40, 55, 0.26)',
    recessHighlightColor: 'rgba(255, 255, 255, 0.88)',
    outerShadowColor: 'rgba(75, 45, 60, 0.14)',
    textPrimary: '#2C1B23',
    textSecondary: '#604652',
    accentLeaf: '#956C7F',
    btnBorder: '#83576C',
    btnHoverBg: 'rgba(131, 87, 108, 0.12)',
  },
};

export interface GreenColorExample {
  id: string;
  nameEn: string;
  nameFa: string;
  hex: string;
  tag: string;
}

export const GREEN_CLAY_SWATCHES: GreenColorExample[] = [
  { id: 'pale-sage', nameEn: 'Pale Sage Clay', nameFa: 'خاک رس سدری ملایم', hex: '#EEF3EB', tag: 'Original' },
  { id: 'matcha-cream', nameEn: 'Matcha Cream', nameFa: 'کرم ماتچای روشن', hex: '#EDF5E4', tag: 'Fresh' },
  { id: 'soft-pistachio', nameEn: 'Creamy Pistachio', nameFa: 'مغز پسته شیری', hex: '#F3F7ED', tag: 'Warm' },
  { id: 'frosted-eucalyptus', nameEn: 'Frosted Eucalyptus', nameFa: 'اکالیپتوس و نعناع', hex: '#E7F2EF', tag: 'Cool' },
  { id: 'jade-celadon', nameEn: 'Jade & Celadon', nameFa: 'یشم و سلادون کهن', hex: '#E0EDE6', tag: 'Mineral' },
  { id: 'forest-dew', nameEn: 'Forest Woodland Dew', nameFa: 'شبنم جنگل کهن', hex: '#E3EDE0', tag: 'Earthy' },
];

export const GREEN_TEXT_SWATCHES: GreenColorExample[] = [
  { id: 'deep-pine', nameEn: 'Imperial Forest Pine', nameFa: 'سبز کاج و جنگل کهن', hex: '#0F2615', tag: 'High Contrast' },
  { id: 'emerald-gem', nameEn: 'Heritage Emerald', nameFa: 'سبز زمردی و یشمی', hex: '#0C2A1E', tag: 'Gemstone' },
  { id: 'roasted-olive', nameEn: 'Roasted Olive', nameFa: 'زیتونی تیره ارگانیک', hex: '#20301B', tag: 'Organic' },
  { id: 'nordic-cypress', nameEn: 'Nordic Cypress', nameFa: 'سبز سرو و کاج تیره', hex: '#132B28', tag: 'Moody' },
  { id: 'sage-cedar', nameEn: 'Classic Sage Cedar', nameFa: 'سدر و خزه کلاسیک', hex: '#1F291E', tag: 'Classic' },
  { id: 'matcha-leaf', nameEn: 'Matcha Tea Leaf', nameFa: 'برگ چای ماتچا', hex: '#192C12', tag: 'Vibrant' },
];

export const DEFAULT_CONFIG_EN: WidgetCustomization = {
  language: 'en',
  brandName: 'Maharat School',
  subtitle: 'I N T R O D U C T I O N',
  title: 'Learn Today,\nLead Tomorrow',
  description: 'Maharat School is a place where curiosity meets opportunity. We nurture confident, compassionate and capable learners who create a brighter future.',
  buttonText: 'Discover Our Story',
  clayTheme: 'sage',
  recessDepth: 'medium',
  tiltEnabled: false,
  showSproutAccent: true,
  leafTopOffset: 19,
  leafRightOffset: 0,
  showDaricheh: true,
  darichehSub: 'ورود به',
  darichehTitle: 'دریچه',
  darichehUrl: 'http://194.48.198.146/auth/login',
  darichehRotate: -10,
  darichehTop: 14,
  darichehLeft: 35,
  showClockWidget: true,
  clockSize: 'normal',
  clockColor: '#E76F51',
  clockTop: 84,
  clockRight: 14,
  clockRotate: 8,
  heroWidth: 1150,
  statBoxSize: 'large',
  statBoxOffset: 60,
  menuTopOffset: 1,
  heroTopGap: 16,
  sliderBadgeSize: 'normal',
  sliderBadgeOffset: 6,
  slides: DEFAULT_SLIDES,
  autoPlaySlider: true,
  sliderInterval: 4.5,
  showSliderControls: true,
};

export const DEFAULT_CONFIG_FA: WidgetCustomization = {
  language: 'fa',
  brandName: 'دبستان پسرانه مهارت',
  subtitle: 'سال تحصیلی ۱۴۰۶–۱۴۰۵ · پیش‌ثبت‌نام',
  title: 'جایی برای بازی\nو یادگیری',
  description: 'اولین مدرسه تخصصی مهارت‌ محور با رویکرد آموزش پروژه محور در مشهد',
  buttonText: 'معرفی مدرسه',
  clayTheme: 'sage',
  recessDepth: 'medium',
  tiltEnabled: false,
  showSproutAccent: true,
  leafTopOffset: 19,
  leafRightOffset: 0,
  showDaricheh: true,
  darichehSub: 'ورود به',
  darichehTitle: 'دریچه',
  darichehUrl: 'http://194.48.198.146/auth/login',
  darichehRotate: -10,
  darichehTop: 14,
  darichehLeft: 35,
  showClockWidget: true,
  clockSize: 'normal',
  clockColor: '#E76F51',
  clockTop: 84,
  clockRight: 14,
  clockRotate: 8,
  heroWidth: 1150,
  statBoxSize: 'large',
  statBoxOffset: 60,
  menuTopOffset: 1,
  heroTopGap: 16,
  sliderBadgeSize: 'normal',
  sliderBadgeOffset: 6,
  slides: DEFAULT_SLIDES,
  autoPlaySlider: true,
  sliderInterval: 4.5,
  showSliderControls: true,
};
